travis:
  secure:
    BINSTAR_TOKEN: ENDFmKlQezzuAFhv0jiYTSesdFUDQAw//OxvflKtiny1zZYMxJ005ZZqdXX4Evie4SQcBOh/ECYin7ma4rti60pcn3hlmkQmiuJ1jUS/P2D+0MXp/dmVfB5oXB4iwys7kN3qv54SPgaJF0DML1caLma36OBdbkJcXhaxGj3gGlerVjuW+swyfIgnjDmzwQa1arU/6srQHv5gTpcRjDqpI5wXuoOKX6NjoqYoTMMXY/7DcGjwOrUrLLllNXWRvvO6uFFxSwb/78Od5kt8HQ1YZm8BMjqxcwCowVpCkTVYHC9WN7aQnhfkeIQ3UCLjJNW7jDbnoYLKXXCfCW4zLiQI4NL1SxyBNnn86dBE95VyjUMesnjkPNefpJb84mc7iyJ5iXHMAuLU0U+f/kaAQcbLta8GHkSPZskr1qU7C73YVGqHNNw92efWnM6bU2f+H6rNuE5FxRXFJ6sXXK2qaIaCE9A8hnO16rBk51NshJV6Dh1Q6x4Dpy+kuWOjJvZXOjOLh7slYhG4wqgpUZClt2WJ2seA/RtT9h8Do6rgGQDjFpWEGZ/JwqikAvLk4Q2B+bxzqHzu1hqCuMYBZ4IDc8IdgWX8V5T1zJaE1y51tbd2gUl6GmxGYShNUHlDwLPv3vA2KMGt4O6e+J09bBYKx5Guz/peIGFAm4d/ygGCN32Atzg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
